#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Docker 컨테이너화 자동화 (Docker Automation)

[Purpose]
Dockerfile 자동 생성, 이미지 빌드, 배포 자동화를 제공합니다.

[Responsibilities]
- Dockerfile 자동 생성 (프로젝트 구조 기반)
- docker-compose.yml 검증 및 최적화
- 이미지 빌드 및 배포 자동화
- Kubernetes 매니페스트 생성 (선택)

[Main Flow]
1. 프로젝트 구조 분석
2. Dockerfile 템플릿 생성
3. docker-compose.yml 검증
4. 이미지 빌드 실행
5. 배포 준비

[Dependencies]
- Python 표준 라이브러리
- Docker CLI

[Author] Copilot
[Created] 2026-02-03
[Modified] 2026-02-03
"""

import os
import sys
import subprocess
import argparse
import yaml
from pathlib import Path
from typing import Dict, List, Optional


class DockerAutomation:
    """Docker 자동화 클래스"""
    
    def __init__(self, repo_root: Path):
        """
        초기화
        
        Args:
            repo_root: 레포지토리 루트 경로
        """
        self.repo_root = repo_root
        self.dockerfile = repo_root / 'Dockerfile'
        self.docker_compose = repo_root / 'docker-compose.yml'
    
    def check_docker(self) -> bool:
        """
        Docker 설치 및 실행 확인
        
        Returns:
            bool: Docker 사용 가능 여부
        """
        try:
            result = subprocess.run(
                ['docker', '--version'],
                capture_output=True,
                timeout=5
            )
            return result.returncode == 0
        except:
            return False
    
    def generate_dockerfile(self, force: bool = False) -> bool:
        """
        Dockerfile 자동 생성
        
        Args:
            force: 기존 파일 덮어쓰기 여부
        
        Returns:
            bool: 생성 성공 여부
        """
        print("\n=== 🐳 Dockerfile 생성 ===\n")
        
        if self.dockerfile.exists() and not force:
            print(f"⚠️  Dockerfile이 이미 존재합니다: {self.dockerfile}")
            print("   --force 옵션으로 덮어쓸 수 있습니다")
            return False
        
        # Python 버전 확인
        python_version = f"{sys.version_info.major}.{sys.version_info.minor}"
        
        # Dockerfile 템플릿
        dockerfile_content = f"""# Upbit Trader - Dockerfile
# Auto-generated by automation/docker_automation.py

FROM python:{python_version}-slim

# 작업 디렉토리 설정
WORKDIR /app

# 시스템 의존성 설치
RUN apt-get update && apt-get install -y \\
    gcc \\
    g++ \\
    && rm -rf /var/lib/apt/lists/*

# Python 의존성 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# 환경 변수 설정
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# 포트 노출
EXPOSE 8000

# 실행 명령
CMD ["python", "src/main.py"]
"""
        
        # Dockerfile 저장
        with open(self.dockerfile, 'w', encoding='utf-8') as f:
            f.write(dockerfile_content)
        
        print(f"✅ Dockerfile 생성 완료: {self.dockerfile}")
        return True
    
    def validate_docker_compose(self) -> Dict:
        """
        docker-compose.yml 검증
        
        Returns:
            Dict: 검증 결과
        """
        print("\n=== 📋 docker-compose.yml 검증 ===\n")
        
        if not self.docker_compose.exists():
            print(f"❌ docker-compose.yml이 존재하지 않습니다: {self.docker_compose}")
            return {
                'success': False,
                'error': 'File not found'
            }
        
        try:
            # YAML 파일 파싱
            with open(self.docker_compose, 'r', encoding='utf-8') as f:
                config = yaml.safe_load(f)
            
            issues = []
            
            # 기본 구조 확인
            if 'version' not in config:
                issues.append("⚠️  버전 정보가 없습니다")
            
            if 'services' not in config:
                issues.append("❌ services 섹션이 없습니다")
                return {
                    'success': False,
                    'issues': issues
                }
            
            services = config['services']
            
            # 필수 서비스 확인
            required_services = ['mongodb', 'redis']
            for service in required_services:
                if service not in services:
                    issues.append(f"⚠️  {service} 서비스가 정의되지 않았습니다")
                else:
                    print(f"✅ {service} 서비스 정의됨")
            
            # 볼륨 확인
            if 'volumes' in config:
                print(f"✅ {len(config['volumes'])}개 볼륨 정의됨")
            
            # 네트워크 확인
            if 'networks' in config:
                print(f"✅ {len(config['networks'])}개 네트워크 정의됨")
            
            if issues:
                print(f"\n발견된 이슈: {len(issues)}개")
                for issue in issues:
                    print(f"  {issue}")
            
            return {
                'success': len(issues) == 0,
                'issues': issues,
                'services': list(services.keys())
            }
        
        except yaml.YAMLError as e:
            print(f"❌ YAML 파싱 오류: {e}")
            return {
                'success': False,
                'error': f'YAML parse error: {e}'
            }
        except Exception as e:
            print(f"❌ 검증 중 오류: {e}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def build_image(self, tag: str = 'latest') -> bool:
        """
        Docker 이미지 빌드
        
        Args:
            tag: 이미지 태그
        
        Returns:
            bool: 빌드 성공 여부
        """
        print(f"\n=== 🔨 Docker 이미지 빌드 (태그: {tag}) ===\n")
        
        if not self.check_docker():
            print("❌ Docker가 설치되지 않았거나 실행 중이지 않습니다")
            return False
        
        if not self.dockerfile.exists():
            print(f"❌ Dockerfile이 존재하지 않습니다: {self.dockerfile}")
            print("   --generate-dockerfile 옵션으로 생성하세요")
            return False
        
        image_name = f"upbit-trader:{tag}"
        
        try:
            result = subprocess.run(
                ['docker', 'build', '-t', image_name, '.'],
                cwd=self.repo_root,
                timeout=600  # 10분 타임아웃
            )
            
            if result.returncode == 0:
                print(f"\n✅ 이미지 빌드 완료: {image_name}")
                return True
            else:
                print(f"\n❌ 이미지 빌드 실패")
                return False
        
        except subprocess.TimeoutExpired:
            print(f"\n❌ 빌드 타임아웃 (10분 초과)")
            return False
        except Exception as e:
            print(f"\n❌ 빌드 중 오류: {e}")
            return False
    
    def deploy(self) -> bool:
        """
        Docker Compose로 배포
        
        Returns:
            bool: 배포 성공 여부
        """
        print("\n=== 🚀 Docker Compose 배포 ===\n")
        
        if not self.check_docker():
            print("❌ Docker가 설치되지 않았거나 실행 중이지 않습니다")
            return False
        
        if not self.docker_compose.exists():
            print(f"❌ docker-compose.yml이 존재하지 않습니다")
            return False
        
        try:
            # docker-compose up -d
            result = subprocess.run(
                ['docker-compose', 'up', '-d'],
                cwd=self.repo_root,
                timeout=300  # 5분 타임아웃
            )
            
            if result.returncode == 0:
                print("\n✅ 배포 완료")
                
                # 실행 중인 컨테이너 확인
                subprocess.run(
                    ['docker-compose', 'ps'],
                    cwd=self.repo_root
                )
                
                return True
            else:
                print("\n❌ 배포 실패")
                return False
        
        except subprocess.TimeoutExpired:
            print("\n❌ 배포 타임아웃 (5분 초과)")
            return False
        except Exception as e:
            print(f"\n❌ 배포 중 오류: {e}")
            return False
    
    def generate_k8s_manifest(self) -> bool:
        """
        Kubernetes 매니페스트 생성
        
        Returns:
            bool: 생성 성공 여부
        """
        print("\n=== ☸️  Kubernetes 매니페스트 생성 ===\n")
        
        k8s_dir = self.repo_root / 'k8s'
        k8s_dir.mkdir(exist_ok=True)
        
        # 간단한 Deployment 매니페스트
        deployment_yaml = """apiVersion: apps/v1
kind: Deployment
metadata:
  name: upbit-trader
  labels:
    app: upbit-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upbit-trader
  template:
    metadata:
      labels:
        app: upbit-trader
    spec:
      containers:
      - name: upbit-trader
        image: upbit-trader:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - secretRef:
            name: upbit-trader-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: upbit-trader-service
spec:
  selector:
    app: upbit-trader
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
"""
        
        deployment_file = k8s_dir / 'deployment.yaml'
        with open(deployment_file, 'w', encoding='utf-8') as f:
            f.write(deployment_yaml)
        
        print(f"✅ Deployment 매니페스트 생성: {deployment_file}")
        
        # Secret 템플릿
        secret_yaml = """apiVersion: v1
kind: Secret
metadata:
  name: upbit-trader-secrets
type: Opaque
stringData:
  UPBIT_ACCESS_KEY: "your-access-key-here"
  UPBIT_SECRET_KEY: "your-secret-key-here"
  MONGODB_URI: "mongodb://mongodb:27017"
  REDIS_HOST: "redis"
"""
        
        secret_file = k8s_dir / 'secret.yaml.template'
        with open(secret_file, 'w', encoding='utf-8') as f:
            f.write(secret_yaml)
        
        print(f"✅ Secret 템플릿 생성: {secret_file}")
        print("\n⚠️  주의: secret.yaml.template을 복사하여 실제 값을 입력하세요")
        
        return True


def main():
    """메인 함수"""
    parser = argparse.ArgumentParser(
        description='Docker 컨테이너화 자동화',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
사용 예시:
  # Dockerfile 생성
  python automation/docker_automation.py --generate-dockerfile
  
  # docker-compose.yml 검증
  python automation/docker_automation.py --validate
  
  # 이미지 빌드
  python automation/docker_automation.py --build
  
  # 배포
  python automation/docker_automation.py --deploy
  
  # Kubernetes 매니페스트 생성
  python automation/docker_automation.py --k8s-manifest
        """
    )
    
    parser.add_argument(
        '--generate-dockerfile',
        action='store_true',
        help='Dockerfile 자동 생성'
    )
    
    parser.add_argument(
        '--validate',
        action='store_true',
        help='docker-compose.yml 검증'
    )
    
    parser.add_argument(
        '--build',
        action='store_true',
        help='Docker 이미지 빌드'
    )
    
    parser.add_argument(
        '--deploy',
        action='store_true',
        help='Docker Compose로 배포'
    )
    
    parser.add_argument(
        '--k8s-manifest',
        action='store_true',
        help='Kubernetes 매니페스트 생성'
    )
    
    parser.add_argument(
        '--tag',
        default='latest',
        help='이미지 태그 (기본값: latest)'
    )
    
    parser.add_argument(
        '--force',
        action='store_true',
        help='기존 파일 덮어쓰기'
    )
    
    args = parser.parse_args()
    
    # 레포지토리 루트 찾기
    repo_root = Path(__file__).parent.parent
    automation = DockerAutomation(repo_root)
    
    success = True
    
    if args.generate_dockerfile:
        success = automation.generate_dockerfile(args.force) and success
    
    if args.validate:
        result = automation.validate_docker_compose()
        success = result['success'] and success
    
    if args.build:
        success = automation.build_image(args.tag) and success
    
    if args.deploy:
        success = automation.deploy() and success
    
    if args.k8s_manifest:
        success = automation.generate_k8s_manifest() and success
    
    if not any([args.generate_dockerfile, args.validate, args.build, args.deploy, args.k8s_manifest]):
        parser.print_help()
    else:
        sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
